### ISSUE TITLE
LD Client with DynamoDBFeatureStore  fails with 'cannot read property error from undefined' on any error with DynamoDB

### ISSUE THREAD

**Issue by mdovhopo** [launchdarkly/node-server-sdk-dynamodb#28]
Hey! I am trying to adopt LD in AWS Serverless and trying to use `DynamoDBFeatureStore` and found a little issue there.

If there is any error with DymamoDB (like lack of permissions or not such table) I receive crash from LD CLient with `cannot read property error from undefined` message.

After some investigation I found out that:
1. config (`DynamoDBFeatureStore(...)(config)`) is [LDOptions](https://github.com/launchdarkly/node-server-sdk/blob/bd85a6c166274bd03c309d8279288f93bb2751b7/index.d.ts#L200)
2. LDOptions does not require [logger](https://github.com/launchdarkly/node-server-sdk/blob/bd85a6c166274bd03c309d8279288f93bb2751b7/index.d.ts#L246)
3. But [DynamoDBFeatureStore](https://github.com/launchdarkly/node-server-sdk-dynamodb/blob/5f617cb4c0a77f6b74ed3c9475bcac55cf0c585c/dynamodb_feature_store.js#L24) actually requires it.
4. So if anything bad happens (like [here](https://github.com/launchdarkly/node-server-sdk-dynamodb/blob/5f617cb4c0a77f6b74ed3c9475bcac55cf0c585c/dynamodb_feature_store.js#L68)), SDK will just crash.

My assumption that logger should not be required in `DynamoDBFeatureStore` (it might be default to something like `console` perhaps).

I might be wrong as well, and it would be nice if someone explains this behavior to me)

Thanks for looking into it :)

**Comment by eli-darkly** [comment]
I haven't tried to reproduce this yet, but your explanation is plausible and would suggest that the SDK is not passing options to the data store correctly. There _is_ a default logger in the SDK (otherwise the SDK itself would fail if none was provided) and it is supposed to have already been added into the config object by that point, but maybe that logic is faulty.

**Comment by eli-darkly** [comment]
If so, that would be a bug in the SDK rather than in this package.

**Comment by mdovhopo** [comment]
Hey @eli-darkly, thanks for your fast response.

If it helps, here is how i am initializing the SDK & store:

```ts
import ld, { LDClient } from 'launchdarkly-node-server-sdk';
import { DynamoDBFeatureStore } from 'launchdarkly-node-server-sdk-dynamodb';

const client = ld.init('the-key', {
    featureStore: DynamoDBFeatureStore(
        'sandbox-launchdarkly-persistent-store'
    )(),
})
```

**Comment by eli-darkly** [comment]
Ah, no, that's not the intended usage. You are supposed to put the return value from `DynamoDBFeatureStore` _directly_ into the `featureStore` property of your configuration, just as the example code in the documentation says to do.

In other words:

```js
const client = ld.init('the-key', {
    featureStore: DynamoDBFeatureStore(
        'the-dynamodb-table'
    ),
})
```

It's true that `DynamoDBFeatureStore` returns a function, but you are not supposed to call that function. That's the mechanism by which the SDK will tell the data store about the SDK's configuration, _including the logger_.

If you try the code above and it works, then there's no bug.

**Comment by eli-darkly** [comment]
There are several places that this is documented (like the README in this repo, and the general online docs about configuring SDKs to use databases), and I believe it's adequately explained in _most_ of them... but currently it's not very clear in the Typedoc documentation for this library, which does not have example code, so we could improve that.

**Comment by mdovhopo** [comment]
Yeah, that is what i tried the first time, but TS types expect other type.

![image](https://user-images.githubusercontent.com/44979703/176616551-2b083366-7d74-4647-9781-2ed4d9a13c86.png)

![image](https://user-images.githubusercontent.com/44979703/176616628-e8d68164-ab2f-49ad-a377-a9e87ed4160f.png)

**Comment by eli-darkly** [comment]
What version of the SDK are you using? The [current type definitions](https://launchdarkly.github.io/node-server-sdk/interfaces/_launchdarkly_node_server_sdk_.LDOptions.html#featureStore) look to me as if it should accept this type.

**Comment by mdovhopo** [comment]
Okay I see. I have been using 5.4.2 version. updated to 6+, and works like a charm, my bad. Thanks for your assistance @eli-darkly!
