### ISSUE TITLE
Any plans to migrate to `aws-sdk` v3?

### ISSUE THREAD

**Issue by teriu** [launchdarkly/node-server-sdk-dynamodb#31]
AWS recently announced the deprecation of `aws-sdk` v2. Do you have a timeframe on migrating to the v3 SDK?

Deprecation info: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#Version_2_x_Support

**Comment by louis-launchdarkly** [comment]
Hello @teriu, thank you for reaching out.

We are planning to move to 3.0 within the maintenance period of 2.x. For information on the maintenance period please see: https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html

Filed Internally as _192338_.

**Comment by kinyoklion** [comment]
Hello @teriu,

The new version of the SDK, v8, supports the v3 SDK.

The new version has a new location and package.

The new version is located here: https://github.com/launchdarkly/js-core/tree/main/packages/sdk/server-node
It also has a new package name, `@launchdarkly/node-server-sdk`.

The dynamodb package is also moved and renamed.

Github: https://github.com/launchdarkly/js-core/tree/main/packages/store/node-server-sdk-dynamodb
Npm: https://www.npmjs.com/package/@launchdarkly/node-server-sdk-dynamodb

Thank you,
Ryan

**Comment by Crafoord** [comment]
Great information @kinyoklion, maybe there should be something in the README of this package that highlights that this package is deprecating going forward? And that these new packages should be used.

**Comment by kinyoklion** [comment]
@Crafoord The readme has been updated. Thank you for the feedback.
